### ISSUE TITLE
No libs folder after gem install and specified procedure could not be found

### ISSUE THREAD

**Issue by jugonzal07** [xml4r/libxml-ruby#114]
After great effort, the libxml ruby gem finally installed but I am still having issues trying to use it.

I receive the following error when trying to run a script dependent on it:

```
C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': 1
27: The specified procedure could not be found.   - C:/Ruby200/lib/ruby/gems/2.0
.0/gems/libxml-ruby-2.8.0/lib/libxml_ruby.so (LoadError)
```

I found [this issue](https://github.com/xml4r/libxml-ruby/issues/42) had similar symptoms and went to add the `libs` directory to the path when I realized my `libxml-2.8.0/lib` directory did not include a `libs` folder-- only `libxml` and `xml`. Did something go wrong when installing the gem? 

I (maybe foolishly) attempted to create a `libs` directory,directly grab the missing .dlls from github, drop them in, and add the new libs folder to %PATH% but still received the same error.

Any thoughts on what could be causing this?

**Comment by cfis** [comment]
The libs folder is a folder that has system dlls like libiconv, libxml2, libz.  There are just there as a convenience if you didn't have them on windows.  So that is not your problem.

The real sounding problem is that libxml_ruby.so was not compiled successfully.  You would need to show the compile log to tell.  Since this is pretty old, I will close.  Reopen if still an issue.
