### ISSUE TITLE
How change encoding attribute in the XML declaration

### ISSUE THREAD

**Issue by esycheva** [xml4r/libxml-ruby#136]
Hello, 

I've created a large XML document successfully and quickly. But I need to use  WINDOWS-1251 encoding in it. 

My code looks like: 

```
require 'xml'

document = XML::Document.new
# add some nodes ...
document.save('foo.xml', :indent => true, :encoding => XML::Encoding::UTF_8)
```

I thought that I could do something like this:

```
xml_string = document.to_s.forse_encoding('windows-1251')
File.open('foo.xml', 'w') { |file| file.write(xml_string) }
```

But if I run this code, the xml declaration would stay 
`"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" `

and may be I would have a perfomance problem.

How change  encoding correctly?

**Comment by julp** [comment]
Hi,

libxml-ruby won't use ruby string's encoding here, just change your constant, `XML::Encoding::UTF_8`, for [one of the supported charsets](http://xml4r.github.io/libxml-ruby/rdoc/index.html) by libxml2 (and libxml-ruby gem by extension).

But CP1251/Windows-1251 is not part of the [*embedded* charsets in libxml2](https://git.gnome.org/browse/libxml2/tree/encoding.c), you have to choose a close charset (ISO-8859-5). *Sadly*, libxml2 can rely on iconv and/or ICU to convert I/O but charset names are quite strongly hardcoded instead of possibly letting iconv/ICU recognize the encoding.

If you absolutely want a document output in CP1251, I guess you can still convert the output string and then replace the prolog:
```ruby
xml_string = document.to_s.encode!(Encoding::CP1251).sub('<?xml version="1.0" encoding="UTF-8"?>', '<?xml version="1.0" encoding="CP1251"?>')
```

**Comment by esycheva** [comment]
@julp, hi!

Thank you for your answer. I'll use your workaround!

Sadly that there isn't a better solution in libxml2.
